services:
    rmcgirr83.upcomingbirthdays.acplistener:
        class: rmcgirr83\upcomingbirthdays\event\acp_listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }

    rmcgirr83.upcomingbirthdays.mainlistener:
        class: rmcgirr83\upcomingbirthdays\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
