services:
    hifikabin.showtransferedpermissions.listener:
        class: hifikabin\showtransferedpermissions\event\listener
        arguments:
            - '@language'
        tags:
            - { name: event.listener }
