services:
    skouat.ppde.core_actions:
        class: skouat\ppde\actions\core
        arguments:
            - '@config'
            - '@language'
            - '@skouat.ppde.notification.core'
            - '@path_helper'
            - '@skouat.ppde.entity.transactions'
            - '@skouat.ppde.operator.transactions'
            - '@dispatcher'
            - '@user'
            - '%core.php_ext%'

    skouat.ppde.actions.auth:
        class: skouat\ppde\actions\auth
        arguments:
            - '@auth'
            - '@config'
            - '%core.root_path%'
            - '%core.php_ext%'

    skouat.ppde.actions.currency:
        class: skouat\ppde\actions\currency
        arguments:
            - '@skouat.ppde.entity.currency'
            - '@skouat.ppde.actions.locale_icu'
            - '@skouat.ppde.operator.currency'
            - '@template'

    skouat.ppde.actions.locale_icu:
        class: skouat\ppde\actions\locale_icu
        arguments:
            - '@config'
            - '@template'
            - '@user'

    skouat.ppde.actions.post_data:
        class: skouat\ppde\actions\post_data
        arguments:
            - '@language'
            - '@skouat.ppde.operator.compare'
            - '@request'

    skouat.ppde.actions.vars:
        class: skouat\ppde\actions\vars
        arguments:
            - '@skouat.ppde.core_actions'
            - '@skouat.ppde.actions.currency'
            - '@config'
            - '@language'
            - '@user'
