services:
    phpbbservices.smartfeed.controller.ui:
        class: phpbbservices\smartfeed\controller\ui
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '@dbal.conn'
            - '@auth'
            - '%core.root_path%'
            - '@phpbbservices.smartfeed.common'
            - '/ext/phpbbservices/smartfeed/'
            - '@language'
    phpbbservices.smartfeed.controller.feed:
        class: phpbbservices\smartfeed\controller\feed
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '@dbal.conn'
            - '@auth'
            - '%core.root_path%'
            - '@request'
            - '@log'
            - '@phpbbservices.smartfeed.common'
            - '@language'
            - '@notification_manager'
    phpbbservices.smartfeed.common:
        class: phpbbservices\smartfeed\core\common
        arguments:
            - '@auth'
    phpbbservices.smartfeed.listener:
        class: phpbbservices\smartfeed\event\main_listener
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
