parameters:
    stevotvr.steamstatus.tables.steamstatus: '%core.table_prefix%steamstatus'
services:
    stevotvr.steamstatus.entity:
        class: stevotvr\steamstatus\entity\steamprofile
        shared: false
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '%stevotvr.steamstatus.tables.steamstatus%'
    stevotvr.steamstatus.operator:
        class: stevotvr\steamstatus\operator\steamprofile
        arguments:
            - '@config'
            - '@service_container'
            - '@dbal.conn'
            - '%stevotvr.steamstatus.tables.steamstatus%'
    stevotvr.steamstatus.operator.openid:
        class: stevotvr\steamstatus\operator\openid
        arguments:
            - '@config'
            - '@request'
            - '@user'
    stevotvr.steamstatus.controller:
        class: stevotvr\steamstatus\controller\main
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@stevotvr.steamstatus.operator'
    stevotvr.steamstatus.listener.main:
        class: stevotvr\steamstatus\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@stevotvr.steamstatus.operator'
            - '@template'
        tags:
            - { name: event.listener }
    stevotvr.steamstatus.cron.task.main:
        class: stevotvr\steamstatus\cron\task\main
        arguments:
            - '@config'
            - '@dbal.conn'
            - '%stevotvr.steamstatus.tables.steamstatus%'
        calls:
            - [set_name, [cron.task.stevotvr.steamstatus]]
        tags:
            - { name: cron.task }
