kinerity_bestanswer_controller:
    path: /answer/{action}
    defaults: { _controller: kinerity.bestanswer.controller:change_post_status }
    requirements:
        action: 'mark_answer|unmark_answer'
