rmcgirr83_stopforumspam_core_reporttosfs:
    path: /reporttosfs/{postid}/{posterid}
    defaults: { _controller: rmcgirr83.stopforumspam.core.reporttosfs:reporttosfs }
    requirements:
        postid:  \d+
        posterid: \d+

rmcgirr83_stopforumspam_core_report_pm_to_sfs:
    path: /report_pm_to_sfs/{msgid}/{authorid}
    defaults: { _controller: rmcgirr83.stopforumspam.core.report_pm_to_sfs:report_pm_to_sfs }
    requirements:
        msgid:  \d+
        authorid: \d+        
