services:
    primehalo.primelinks.listener:
        class: primehalo\primelinks\event\main_listener
        arguments:
            - @template
            - @user
            - @config
        tags:
            - { name: event.listener }
