services:
    threedi.os.controller.acp:
        class: threedi\os\controller\acp_controller
        arguments:
            - '@config'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    threedi.os.listener:
        class: threedi\os\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
