services:
    dmzx.membertimecounter.listener:
        class: dmzx\membertimecounter\event\listener
        arguments:
            - @template
            - @user
        tags:
            - { name: event.listener }
 