parameters:
    contact_constants:
        CONFIRM_CONTACT: 4
        CONTACT_METHOD_EMAIL: 0
        CONTACT_METHOD_POST: 1
        CONTACT_METHOD_PM: 2
        CONTACT_METHOD_BOARD_DEFAULT: 3
        CONTACT_POST_NEITHER: 0
        CONTACT_POST_GUEST: 1
        CONTACT_POST_ALL: 2
