<?php
//
// File generated by Dolibarr installer 19.0.1 on apr 11, 2024
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://www.doctorwhofans.be/dolibarr/htdocs';
$dolibarr_main_document_root='/customers/e/a/c/doctorwhofans.be/httpd.www/dolibarr/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/customers/e/a/c/doctorwhofans.be/httpd.www/dolibarr/htdocs/custom';
$dolibarr_main_data_root='/customers/e/a/c/doctorwhofans.be/httpd.www/dolibarr/documents';
$dolibarr_main_db_host='doctorwhofans.be.mysql';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='doctorwhofans_be_management';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='doctorwhofans_be_management';
$dolibarr_main_db_pass='SS7kTeFdxCnRidChu6d4iBnmxUTRnodv';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='1';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pgrestore, clamdscan, clamscan.exe';
$dolibarr_nocsrfcheck='1';
$dolibarr_main_instance_unique_id='37689c5c5178088890c2c8e41d2ec842';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
