rmcgirr83_whoposted_core_whoposted:
    path: /whoposted/{forum_id}/{topic_id}
    requirements:
        forum_id: \d+
        topic_id: \d+
    defaults: { _controller: rmcgirr83.whoposted.core.whoposted:whoposted }
