services:
    rmcgirr83.whoposted.core.whoposted:
        class: rmcgirr83\whoposted\core\whoposted
        arguments:
            - '@auth'
            - '@content.visibility'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
    rmcgirr83.whoposted.listener:
        class: rmcgirr83\whoposted\event\listener
        arguments:
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
