services:
    rmcgirr83.zodiacs.listener:
        class: rmcgirr83\zodiacs\event\listener
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
