rmcgirr83_posteripinviewtopic_core_freegeoip:
    path: /freegeoip/{post_id}
    defaults: { _controller: rmcgirr83.posteripinviewtopic.core.freegeoip:freegeoip }
    requirements:
        post_id: \d+
