services:
    rmcgirr83.posteripinviewtopic.listener:
        class: rmcgirr83\posteripinviewtopic\event\listener
        arguments:
            - '@auth'
            - '@language'
            - '@template'
            - '@controller.helper'
        tags:
            - { name: event.listener }

    rmcgirr83.posteripinviewtopic.core.freegeoip:
        class: rmcgirr83\posteripinviewtopic\core\freegeoip
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '%tables%'
